# Dependabot version updates. See docs for configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/app/"
    schedule:
      interval: "monthly"
    ignore: # only update minor or major version changes
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      fontawesome:
        patterns:
          - "@fortawesome*"
    # Increase the minimum version for all npm dependencies (instead of expanding the range)
    versioning-strategy: increase
