# Dependabot version updates. See docs for configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "quarterly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/app/"
    schedule:
      interval: "quarterly"
    ignore: # only update minor or major version changes
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      fontawesome:
        patterns:
          - "@fortawesome/*"
      material-ui:
        patterns:
          - "@emotion/*"
          - "@mui/*"
      next:
        patterns:
          - "@next/*"
          - "next"
      photo-gallery:
        patterns:
          - "react-photo-album"
          - "yet-another-react-lightbox"
      react:
        patterns:
          - "react"
          - "react-dom"
      remark:
        patterns:
          - "remark*"
      tailwind:
        patterns:
          - "postcss"
          - "@tailwindcss*"
          - "tailwindcss*"
    # Increase the minimum version for all npm dependencies (instead of expanding the range)
    versioning-strategy: increase
    open-pull-requests-limit: 10
